name: twilio_programmable_voice
description: Non-official Flutter Twilio API for Twilio Programmable Voice Resource
version: 0.0.1
author: 'izio38'
homepage: 'https://github.com/izio38/'

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^5.0.1+1 # https://pub.dev/packages/permission_handler
  soundpool: ^1.1.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  background_fetch: '^0.7.1'
  # workmanager:
  #   git:
  #     url: git://github.com/Pierre-Monier/flutter_workmanager.git
  #     ref: workmanager-factory
  jwt_decoder: ^1.0.3
  # firebase_messaging: 7.0.3
  flutter_apns: ^1.4.1
  dio: ^3.0.10
  meta: ^1.2.4
  uuid: ^2.2.2
  get_it: ^5.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.12
  mockito: ^4.1.4
  http_mock_adapter: ^0.1.5
  start_jwt: ^0.2.0

flutter:
  plugin:
    platforms:
      android:
        package: fr.izio.twilio_programmable_voice
        pluginClass: TwilioProgrammableVoicePlugin
      ios:
        pluginClass: SwiftTwilioProgrammableVoicePlugin
  assets:
    - packages/twilio_programmable_voice/assets/sounds/disconnect.wav
    - packages/twilio_programmable_voice/assets/sounds/incoming.wav
    - packages/twilio_programmable_voice/assets/sounds/outgoing.wav

